### PR TITLE
Move Ben

### PR DESCRIPTION
**Pull request by AbhiAgarwal**
Move Ben to alumni. I'm not sure whether to do this - that's why I do a pull request.

### CODE REVIEW

**Comment by grungerabbit** [comment]
I wasn't sure based on the comment `and (unofficially) Ben` on the org chart: https://github.com/TechAtNYU/techatnyu-private/wiki/Organization-Chart-&-Team-Goals ...

**Comment by freialobo** [comment]
I think it's safe to do so, because he specifically said he didn't have time for eboard but would like to stay involved in some capacity.

**Comment by ethanresnick** [comment]
+1

**Comment by AbhiAgarwal** [comment]
Confirmed!

**Pull request merged**
