### PR TITLE
Update max-stoller.md.

### PR DESCRIPTION
**Pull request by maxstoller**
Can you please merge this for me? 👍

(cc @grungerabbit)

### CODE REVIEW

**Comment by grungerabbit** [comment]
Done. thanks @maxstoller!

**Comment by maxstoller** [comment]
Awesome, thanks a lot @grungerabbit. Who's in charge of deploying it?

**Comment by grungerabbit** [comment]
Me! or @AbhiAgarwal. I can have it up by 1/16 (it may happen before then). Do you want me to ping you when it's up?

**Comment by maxstoller** [comment]
That would be great. Thanks again!

**Comment by maxstoller** [comment]
@grungerabbit -- Just checking in. Any chance you can push this for me? Thanks again.

**Comment by grungerabbit** [comment]
hey @maxstoller, thanks for your patience! Should be live now on ship.techatnyu.org :D

**Comment by maxstoller** [comment]
:fireworks: :+1: Thanks!

**Pull request merged**
